# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1  
ENV PYTHONUNBUFFERED=1  

# Set the working directory in the container
WORKDIR /PERMISSIONS

# Copy the requirements file and install dependencies
COPY requirements.txt /PERMISSIONS/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Django project into the container
COPY . /PERMISSIONS/

# Run migrations and start the Django development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
