# Generated by Django 5.0.6 on 2024-08-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_image', models.ImageField(upload_to='uploads/')),
                ('stu_name', models.CharField(max_length=100)),
                ('stu_roll', models.CharField(max_length=5)),
                ('stu_mobile', models.BigIntegerField(default=0)),
                ('stu_address', models.TextField(max_length=200)),
            ],
        ),
    ]
