// Write a programm to sum of number generated by loop.

// let sum=0;
// for(let i=1; i<=10 ; i+=2){
//     sum=sum+i
//     console.log(i)
// }
// console.log(sum)

// Write a program to product of number generate by loop.
// let s=1
// let e=15
// for(s;s<=e;s++){
//     console.log(s)
// }


// Write a programme to print the table of a number given by user.
let user=3
for(let i=1 ; i<=10 ; i++){
    console.log(`${user} x ${i} = ${user*i}`)
}