# Generated by Django 5.1.1 on 2024-09-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=200)),
                ('stu_mobile', models.CharField(max_length=12)),
                ('stu_roll', models.CharField(max_length=200)),
                ('stu_address', models.TextField()),
            ],
        ),
    ]
