# Generated by Django 5.0.6 on 2024-08-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='cus_balance',
            field=models.BigIntegerField(null=True),
        ),
    ]
