# Generated by Django 5.0.6 on 2024-08-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_alter_customerdata_cus_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='cus_acc_no',
            field=models.CharField(default='2518852338', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='cus_balance',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
