# Generated by Django 4.2.16 on 2024-10-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_ac_no', models.CharField(max_length=10, null=True)),
                ('cus_ac_holder', models.CharField(max_length=10, null=True)),
                ('cus_mob', models.CharField(max_length=10, null=True)),
                ('cus_address', models.CharField(max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
